spring.application.name=app-ui

spring.datasource.url=jdbc:postgresql://localhost:5432/app-db
spring.datasource.username=deivy
spring.datasource.password=#Duocore

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

app.path.payments.files=/media/d31vy/hd01/Pagamentos/Pagamentos_PF/