spring.application.name=app-api

server.port=8081
#server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://localhost:5432/app-db
spring.datasource.username=deivy
spring.datasource.password=#Duocore

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.packages-to-scan=com.br.api.restcontroller
springdoc.packagesToScan=com.br.api.restcontroller
springdoc.pathsToMatch=/api/v1/**

spring.jpa.open-in-view=false

app.path.payments.files=/media/d31vy/hd01/Pagamentos/Pagamentos_PF/